services:
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.13-management'
    environment:
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_USER: admin
    ports:
      - '5672:5672'
      - '15672:15672'