POST http://localhost:80/ms-authentication/api/v1/auth/sign-up
Content-Type: application/json

{
    "firstName": "Joel",
    "lastName": "Filho",
    "email": "joelf.pessoal@gmail.com",
    "password": "12345678",
    "taxId": "60422410365"
}

###

POST http://localhost:80/ms-authentication/api/v1/auth/sign-in
Content-Type: application/json

{
    "taxId": "60422410365",
    "password": "12345678"
}