spring:
  application:
    name: ms-authentication
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:8080/realms/bank.com.br}

server:
  port: ${PORT:8081}
  servlet:
    context-path: /ms-authentication/api/v1