spring:
  application:
    name: ms-authentication
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:8080/realms/bank.com.br}

server:
  port: ${PORT:8081}
  servlet:
    context-path: /ms-authentication/api/v1
  
gateway:
  url: ${GATEWAY_URL:http://localhost:8080}
  auth:
    realm: ${KEYCLOAK_REALM:bank.com.br}
    client-id: ${KEYCLOAK_CLIENT_ID:ms-authentication}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:dXZjH1R0CQuwE72EdDDPZ9qvXA5Osty8}
    grant-type: ${KEYCLOAK_GRANT_TYPE:password}
    admin:
      grant-type: ${KEYCLOAK_ADMIN_GRANT_TYPE:client_credentials}

logging:
  level:
    '[br.com.joelf.msauthentication.infrastructure]': DEBUG