services:
  api: &api
    build: .
    env_file:
      - ./environments/.env
    depends_on:
      - db
      - redis
    networks:
      - rabbitmq_network
      - services_network

  db:
    image: postgres
    restart: always
    hostname: db
    env_file:
      - ./environments/.env         
    ports:
      - '5432:5432'
    networks:
      - services_network

  redis:
    image: redis
    hostname: redis
    restart: always
    env_file:
      - ./environments/.env
    ports:
      - '6379:6379'  
    networks:
      - services_network

networks:
  rabbitmq_network:
    external:
      name: bankcombr_rabbitmq_network
  services_network:
    driver: bridge