services:
  db:
    container_name: ms-transaction-db
    image: postgres
    restart: always
    hostname: db
    env_file:
      - ms-transaction/environments/.env  
    ports:
      - '5432:5432'
    networks:
      - shared_network

  redis:
    container_name: ms-transaction-redis
    image: redis
    hostname: redis
    restart: always
    env_file:
      - ms-transaction/environments/.env
    ports:
      - '6379:6379'  
    networks:
      - shared_network

networks:
  shared_network:
    external: true