services:
  api: &api
    build: 
      context: ms-transaction
      dockerfile: Dockerfile
    env_file:
      - ms-transaction/environments/.env
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - rabbitmq_network
      - services_network
    ports:
      - '8080:8080'

  db:
    image: postgres
    restart: always
    hostname: db
    env_file:
      - ms-transaction/environments/.env  
    ports:
      - '5432:5432'
    networks:
      - services_network

  redis:
    image: redis
    hostname: redis
    restart: always
    env_file:
      - ms-transaction/environments/.env
    ports:
      - '6379:6379'  
    networks:
      - services_network

networks:
  rabbitmq_network:
    external:
      name: bankcombr_rabbitmq_network
  services_network:
    driver: bridge