spring:
  application:
    name: ms-transaction
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/transaction-db}
    username: ${POSTGRES_USER:docker}
    password: ${POSTGRES_PASSWORD:docker}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}
    template:
      retry:
        enabled: true
        initial-interval: 5s

amqp:
  queue:
    transaction:
      name: RABBIT.TRANSACTION.QUEUE
    max-retries: 5

authorizer:
  url: ${AUTHORIZER_URL:https://util.devi.tools}
  path: ${AUTHORIZER_PATH:api/v2/}

jwt:
  secret: ${JWT_SECRET:secret}
  expiration: ${JWT_EXPIRATION:3600}
  